### ISSUE TITLE
Variables in proxies don't have a fixed location

### ISSUE THREAD

**Issue by maxsam4** [PolymathNetwork/polymath-core#275]
The proxy contracts in development-1.5.0 branch have critical variables such as __upgradeabilityOwner, __implementation defined at non-fixed locations. This means that the compiler will assign them storage slots from the start.

Unless we define these variables (or unused, waste variables) at the beginning of all implementations as well, The implementation's own variables will also get assigned the same storage slot by the compiler (Compiler always starts assigning slots from position 0). Consequently, the implementation will overwrite the critical proxy variables when it will try to update its own variables. This will render the proxy useless.

To avoid this overwriting, define a constant location for the critical variables. For example,
`bytes32 private constant IMPLEMENTATION_SLOT = keccak256("polymath.proxy.implementation")`

Then use assembly to store and load the implementation address at/from that storage slot specifically. Constants are not assigned any storage slot in EVM and hence cannot be overwritten by the implementations.

**Comment by satyamakgec** [comment]
Hey, @maxsam4 Thanks to sneak in our smart contracts. But I am not totally agree with you because We are not using the `unstructured proxy patterns` where you need to assign the storage slot because of the overwriting problem. But in `EternalStroage` proxy patterns, this problem does not exist
you can understand with this simple smart contract ex - 

         contract Proxy {
             address private __upgradeabilityOwner;
             address internal __implementation;
             mapping(bytes32 => uint256) internal uintStorage;
             mapping(bytes32 => string) internal stringStorage;
             mapping(bytes32 => address) internal addressStorage;
             mapping(bytes32 => bytes) internal bytesStorage;
             mapping(bytes32 => bool) internal boolStorage;
             mapping(bytes32 => int256) internal intStorage;
             mapping(bytes32 => bytes32) internal bytes32Storage;
         }
  
You are allocating all the storage location at the time of deployment of Proxy contract and you are never going to declare any other variable again while in `unstructured proxy approach` there is a high chance of declaring variable again in the newer version of the smart contract that may lead to the overwriting problem of storage.

So in the above proxy contract you are assigning stroage locations as - 
**Note** - contract have the astronomically larze size ~ `2^256 - 1`

Starting from 0 slot (32 bytes) which store `__upgradeabilityOwner` as address takes 20 bytes 
1 slot store  `__implementation` (takes 20 bytes again).
and then some calculative location for all mappings as they are dynamically sized. using the formula - 
`keccak256(key . (v's slot))` where v is the mapping.

So there is no chance where non-upgradeable variables will be overwriting until unless there is a problem in EVM to allocate the storage for the mappings or for any unforeseen conditions

I think using this approach we don't need to define constant storage slots to non-upgradeable storage variables. If you think I am incorrect anywhere then happy to discuss :).

**Comment by maxsam4** [comment]
Hey @satyamakgec, Thanks for clearing the things. I see that you are using Key Value Storage technique in most contracts. 

Some of the contracts I saw didn't implement the key value concept and that's when I thought something is wrong. I guess those contacts aren't meant to be upgradable or are currently being refractored.

I would also like to add that Unstructured proxy storage technique can also be combined with key value storage which will eliminate the "high chance of declaring variable again in the newer version of the smart contract that may lead to the overwriting problem of storage." while still keeping the option of upgrading storage open. Upgrading storage would probably never be required when using key value technique though.

**Comment by satyamakgec** [comment]
Yes, we are not declaring the proxy variables in the Eternal storage, Above contract is only used for the understanding purpose `How storage will work?`.  

Closing this issue.
