### ISSUE TITLE
Potential Bug in ManualApprovalTransferManager 

### ISSUE THREAD

**Issue by ghost** [PolymathNetwork/polymath-core#456]
Hi,

I was looking through the ManualApprovalTransferManager code and was just wondering if 

https://github.com/PolymathNetwork/polymath-core/blob/12b16806de543fe041627bb5d5547af82b05150b/contracts/modules/TransferManager/ManualApprovalTransferManager.sol#L98-L103

should   ```return Result.ForceValid``` instead of ```Result.Valid```.

https://github.com/PolymathNetwork/polymath-core/blob/12b16806de543fe041627bb5d5547af82b05150b/contracts/modules/TransferManager/ManualApprovalTransferManager.sol#L82

The above implies that MATM should bypass other restrictions, and this applies for the approval case as well. 

At the current state, since in 
https://github.com/PolymathNetwork/polymath-core/blob/12b16806de543fe041627bb5d5547af82b05150b/contracts/tokens/SecurityToken.sol#L629

If another module returns Result.INVALID, then isInvalid will be true, causing verifyTransfer to return false and hence cause the transaction to fail. 

This defeats the purpose of MATM which suppose to bypass all other restrictions and transfer modules for both the block and approvals of transactions.

Thanks!

**Comment by adamdossa** [comment]
Hey @xAffinity - thanks for looking at this.

This is by design - the MATM is allowed to override TransferManagers that return NA (e.g. the GeneralTransferManager if addresses are not on it's list), but not override a TM that returns INVALID (e.g. if an address has traded over its volume restriction in the VolumeRestrictionTM).

For transfers that really need to be forced through, regardless of any restrictions, the issuer can use the forceTransfer method directly.
