### ISSUE TITLE
Migration failure with truffle 0.5.0

### ISSUE THREAD

**Issue by joequant** [PolymathNetwork/polymath-core#630]
Getting failures running truffle migrate with 0.5.0

First truffle-config should explicitly put the compiler version as there are solidity 0.5.0 issues

There are some type conversion errors which can be fixed by explicit casting

```
--- a/migrations/2_deploy_contracts.js
+++ b/migrations/2_deploy_contracts.js
@@ -46,12 +46,12 @@ module.exports = function (deployer, network, accounts) {
         UsdToken = mockedUSDToken.address;
       });
     });
-    deployer.deploy(MockOracle, PolyToken, "POLY", "USD", new BigNumber(0.5).times(new BigNumber(10).pow(18)), {from: PolymathAccount}).then(() => {
+      deployer.deploy(MockOracle, PolyToken, web3.utils.asciiToHex("POLY"), web3.utils.asciiToHex("USD"), new BigNumber(0.5).times(new BigNumber(10).pow(18)), {from: PolymathAccount}).then(() => {
       MockOracle.deployed().then((mockedOracle) => {
         POLYOracle = mockedOracle.address;
       });
     });
-    deployer.deploy(MockOracle, 0, "ETH", "USD", new BigNumber(500).times(new BigNumber(10).pow(18)), {from: PolymathAccount}).then(() => {
+      deployer.deploy(MockOracle, "0x0000000000000000000000000000000000000000" , web3.utils.asciiToHex("ETH"), web3.utils.asciiToHex("USD"), new BigNumber(500).times(new BigNumber(10).pow(18)), {from: 
PolymathAccount}).then(() => {
       MockOracle.deployed().then((mockedOracle) => {
         ETHOracle = mockedOracle.address;
       });
```

But there is another error I can't seem to figure out

```
TypeError: ModuleRegistryProxy.at(...).upgradeToAndCall is not a function
    at deployer.deploy.then.then.then.then.then.then (/home/joe/bench/git/polymath-core/migrations/2_deploy_contracts.js:144:64)
    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deferredchain.js:20:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.10 (core: 5.0.10)
Node v10.14.2
```

**Comment by maxsam4** [comment]
>First truffle-config should explicitly put the compiler version as there are solidity 0.5.0 issues

By default, we use the native solc installed on your machine as it is 10 times faster than solcjs (in dev-3.0.0 branch and onwards). You can configure truffle config to use solcjs if you have an incompatible version of native solc on your machine. Perhaps we should document this better.

>There are some type conversion errors which can be fixed by explicit casting

This is because some web3 versions behave differently than others. I recommend that you run `yarn install` and then try again.

> But there is another error I can't seem to figure out

Can you please tell me which branch you are using?

**Comment by joequant** [comment]
Running master

**Comment by joequant** [comment]
Found the problem
at returns a promise and not a value.  

Putting in some fixes.

**Comment by maxsam4** [comment]
> Running master

We don't support Truffle 5.X on the master branch yet. To use truffle on master branch, install truffle 4.X and other dependencies locally using `yarn install` and then you can use truffle locally via 
`node_modules/.bin/truffle compile`
`node_modules/.bin/truffle test`
`node_modules/.bin/truffle migrate`
etc

Our development branch `dev-3.0.0` uses truffle 5.X and we'll eventually merge it in master.

As far as that error is concerned, in Truffle 4, we are able to do stuff like
```
ModuleRegistryProxy.at(ModuleRegistryProxy.address).upgradeToAndCall("1.0.0", ModuleRegistry.address, bytesProxyMR, {from: PolymathAccount});
```
However, in truffle 5, we have to do it like
```
let mpInstance = await ModuleRegistryProxy.at(ModuleRegistryProxy.address);
await mpInstance.upgradeToAndCall("1.0.0", ModuleRegistry.address, bytesProxyMR, {from: PolymathAccount});
```

This is becuase `.at` command in truffle 5 returns a promise that resolves to the instance rather than returning the instance directly.

**Comment by maxsam4** [comment]
@joequant Thanks for your efforts but we would like to avoid changing dependencies in the master branch. We want to keep master branch such that it represents the current state of deployed contracts. This is not the only change that Truffle 5 has. None of our tests will work if you use Truffle 5.X on master as truffle 5.x uses web3 1.0 while truffle 4 uses web3 0.20 and our test cases in master branch are based on web3 0.20.

That being said, we have already incorporated all the changes in our development branch, `dev-3.0.0` and they will eventually get merged to master AFTER an audit.

**Comment by joequant** [comment]
OK Thanks for the info.  Will work on dev-3.0.0 then

**Comment by maxsam4** [comment]
Closing this Issue now. Feel free to reopen or file a new Issue if you face any other problem.
