### ISSUE TITLE
Allowing the issuer to "delete" token and start again

### ISSUE THREAD

**Issue by pabloruiz55** [PolymathNetwork/polymath-core#68]
Say issuer has ticker and token ZZZ. They make a mistake at some point and they want to start over and still use ZZZ.

In a typical ICO scenario, they would just forget about the token they had and create a new one.

Here, it's a bit more tricky as they would have to "delete" the reservation on the ticker and on the ST Registries.

Does it make sense to support this feature?

**Comment by adamdossa** [comment]
Hmm - I am going to go out on a limb and say it doesn't really make sense to support this unless the original token is somehow "destroyed" and unreferenced from moduleRepository, STR etc.

Otherwise, there will effectively be two Polymath tokens with the same symbol knocking around.

I guess the main reasons for needing to start over, would be if there is a mistake in the decimals, company name part of the token. Both of these are quite hard to get wrong.

**Comment by pabloruiz55** [comment]
Yeah, just wondering if it made sense to add this functionality as I was asked a few times about it. I agree that there's only a few things you need to do and it's hard to get wrong.
