### ISSUE TITLE
Should we hard set the locked value as `true` for type 3 module factory ?

### ISSUE THREAD

**Issue by satyamakgec** [PolymathNetwork/polymath-core#76]
As per the business logic, Type 3 module factory always have the locked value `true`. So once it gets attached to the ST it will not be replaced by another STO?

@adamdossa  @pabloruiz55 Thoughts?

**Comment by adamdossa** [comment]
In general it shouldn't be possible to replace the STO.

Thinking about it, we should have logic that allows you to 'lock' a module type after deploying the module, so that you can:

1. Add an STO module
2. [some time passes]
3. Replace the STO module with a new one due to changing requirements.
4. Lock the STO module.
5. STO starts.

@pabloruiz55 WDYT?

**Comment by pabloruiz55** [comment]
IMHO module types should have the possibility of forcing the modules to always be locked or not.
In the case of STOs, there should be no possibility of setting them to unlocked.

**Comment by adamdossa** [comment]
I was thinking of some cases where an Issuer may even want to attach more than one STO (e.g. an STO for raising in POLY, and a separate STO for raising in ETH, or an STO whose purpose is to manage pre-sale or vesting allocations). Not sure I see the advantage of automatically locking particular types rather than leaving it at investor discretion? From an investors perspective the "investor dashboard" can make it clear which module types have been locked, and possibly warn if the STO type has not yet been locked. Or perhaps the mint function only allows STOs to mint tokens if they have been locked?

**Comment by pabloruiz55** [comment]
I agree, let's leave it as it is.
We can explore this other topic: 

> Thinking about it, we should have logic that allows you to 'lock' a module type after deploying the module, so that you can:
> 
> Add an STO module
> [some time passes]
> Replace the STO module with a new one due to changing requirements.
> Lock the STO module.
> STO starts.
